# Generated by Django 5.1.5 on 2025-04-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='quantite',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
