# Generated by Django 5.2 on 2025-04-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0004_alter_categorie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
