# Generated by Django 5.1.5 on 2025-04-06 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('produits', models.ManyToManyField(related_name='commandes_PFE', to='Categories.produit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_PFE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
