# Generated by Django 5.1.5 on 2025-04-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PFE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='adresse_livraison',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='quantite',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]

