# Generated by Django 5.2 on 2025-04-10 15:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PFE', '0003_userappearancepreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
