# Generated by Django 5.2 on 2025-04-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PFE', '0004_commande_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='Methode_paiement',
            field=models.CharField(default='Carte de crédit', max_length=50),
        ),
    ]
