# Generated by Django 5.2 on 2025-06-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PFE', '0005_commande_methode_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('quantite', models.PositiveIntegerField()),
            ],
        ),
    ]
