# Generated by Django 5.2 on 2025-06-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PFE', '0006_produit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produit',
        ),
        migrations.AddField(
            model_name='commande',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
