# Generated by Django 5.2 on 2025-06-13 12:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0005_produit_slug'),
        ('PFE', '0008_remove_commande_created_at_remove_commande_produits_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='commande',
            name='produits',
            field=models.ManyToManyField(related_name='commandes_PFE', to='Categories.produit'),
        ),
        migrations.AddField(
            model_name='commande',
            name='quantite',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commande',
            name='Methode_paiement',
            field=models.CharField(default='Carte de crédit', max_length=50),
        ),
        migrations.AlterField(
            model_name='commande',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='commande',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_PFE', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LigneCommande',
        ),
    ]
