# Generated by Django 5.2 on 2025-06-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PFE', '0010_lignecommande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='produits',
        ),
    ]
